version: '3.1'
services:
    web:
        build: .
        restart: always
        depends_on:
            - mariadb
    mariadb:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
        ports: [3306]
