version: '3.1'
services:
    web:
        container_name: web
        build: .
        restart: always
        depends_on:
            - mariadb
        links:
            - mariadb
        volumes:
            - /var/lib/mysql
    mariadb:
        container_name: mariadb
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: test
        ports: [3306]
